/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        fintech: {
          bg: '#F7F8FA',
          surface: '#FFFFFF',
          text: '#1A1F36',
          muted: '#6B7280',
          border: '#E5E7EB',
          accent: '#528FF0',
          accentHover: '#3D7CE5',
          accentLight: '#EFF6FF',
          navy: '#0C2340',
          dark: '#2B2F42',
          success: '#16A34A',
          successLight: '#F0FDF4',
          warning: '#D97706',
          warningLight: '#FFFBEB',
          error: '#DC2626',
          errorLight: '#FEF2F2',
        },
        executive: {
          bg: '#F7F8FA',
          card: '#FFFFFF',
          cardHover: '#F9FAFB',
          cardBorder: '#E5E7EB',
          borderSubtle: '#F1F5F9',
          borderHighlight: '#CBD5E1',
          input: '#FFFFFF',
          muted: '#6B7280',
          text: '#1A1F36',
          textSecondary: '#6B7280',
          emerald: '#16A34A',
          emeraldMuted: 'rgba(22, 163, 74, 0.08)',
          blue: '#528FF0',
          blueMuted: 'rgba(82, 143, 240, 0.08)',
          amber: '#D97706',
          amberMuted: 'rgba(217, 119, 6, 0.08)',
          rose: '#DC2626',
          roseMuted: 'rgba(220, 38, 38, 0.08)',
          purple: '#7C3AED',
          purpleMuted: 'rgba(124, 58, 237, 0.08)',
        },
        theme: {
          main: '#F7F8FA',
          secondary: '#FFFFFF',
          sidebar: '#FFFFFF',
          input: '#FFFFFF',
          hover: '#F9FAFB',
          border: '#E5E7EB',
          borderSubtle: '#F3F4F6',
        },
        figma: {
          bg: '#F7F8FA',
          sidebar: '#FFFFFF',
          card: '#FFFFFF',
          cardHover: '#F9FAFB',
          cardBorder: '#E5E7EB',
          borderSubtle: '#F3F4F6',
          emerald: '#16A34A',
          cyan: '#0284C7',
          amber: '#D97706',
          rose: '#DC2626',
          purple: '#7C3AED',
          muted: '#6B7280',
          text: '#1A1F36',
        },
      },
      fontFamily: {
        sans: ['"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'ui-monospace', 'monospace'],
      },
    },
  },
  plugins: [],
}
